
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Congreso Tecnológico",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
  
        <GoogleOAuthProvider clientId="519825759445-emt3s1che35dm22g5bau1he2pi6tcv9o.apps.googleusercontent.com">
          <main>{children}</main>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
